### PR TITLE
fixes #17 Incorrect platform compatibility check

### LINKED ISSUE #17: Incorrect platform compatibility check
The version check string in lib/mdb/mdb.js is checking the wrong line:

```
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b /home/rui]# DEBUG=debug-school node `which node-debug-school`
  debug-school Executing shell command: coreadm -e process;coreadm -p cores/core.%p;ulimit -c unlimited;node --abort-on-uncaught-exception -e 'console.log(process.pid); undef();' +0ms
Checking if platform is supported.  debug-school STDOUT: 71943
  debug-school  +437ms
  debug-school STDERR:Uncaught ReferenceError: undef is not defined
  debug-school 
  debug-school FROM
  debug-school [eval]:1:27
  debug-school Object.exports.runInThisContext (vm.js:74:17)
  debug-school Object.<anonymous> ([eval]-wrapper:6:22)
  debug-school Module._compile (module.js:460:26)
  debug-school evalScript (node.js:431:25)
  debug-school startup (node.js:90:7)
  debug-school node.js:814:3
  debug-school  +3ms
  debug-school err: Error: Command failed: /bin/sh -c coreadm -e process;coreadm -p cores/core.%p;ulimit -c unlimited;node --abort-on-uncaught-exception -e 'console.log(process.pid); undef();'
  debug-school Uncaught ReferenceError: undef is not defined
  debug-school 
  debug-school FROM
  debug-school [eval]:1:27
  debug-school Object.exports.runInThisContext (vm.js:74:17)
  debug-school Object.<anonymous> ([eval]-wrapper:6:22)
  debug-school Module._compile (module.js:460:26)
  debug-school evalScript (node.js:431:25)
  debug-school startup (node.js:90:7)
  debug-school node.js:814:3
  debug-school  +1ms
  debug-school Trying to load mdb's v8 module... +2ms
Checking if platform is supported..  debug-school mdb STDERR:  +343ms
  debug-school mdb STDOUT: mdb_v8 version: 1.3.0 (release, from 28f2bfa)
  debug-school V8 version: 3.28.71.19
  debug-school Autoconfigured V8 support from target
  debug-school C++ symbol demangling enabled
  debug-school  +0ms
Sorry, your current platform is not supported.
Please point your browser to https://github.com/joyent/node-debug-school for more info on which
platforms are supported.
```

This code checks `lines[0]` which is `mdb_v8 version: 1.3.0 (release, from 28f2bfa)` but expects `lines[1]` which is `V8 version: 3.28.71.19`
```
exports.v8ModuleLoaded = function v8ModuleLoaded(output) {
  assert(typeof output === 'string', 'output needs to be a string');

  var lines = output.split('\n');
  if (lines && lines[0].trim().match(/V8 version: \d+\.\d+\.\d+/)) {
    return true;
  }

  return false;
}
```

### PR DESCRIPTION
**Pull request by rjloura**

### CODE REVIEW

File: lib/mdb/mdb.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ exports.v8ModuleLoaded = function v8ModuleLoaded(output) {
   assert(typeof output === 'string', 'output needs to be a string');
 
   var lines = output.split('\n');
-  if (lines && lines[0].trim().match(/V8 version: \d+\.\d+\.\d+/)) {
+  if (lines && lines[0].trim().match(/(V8|mdb_v8) version: \d+\.\d+\.\d+/)) {
```
Comment (misterdjules) [inline lib/mdb/mdb.js]: The output depends on which mdb_v8 version is loaded. With versions < 1.3, I believe mdb_v8 would not output its own version number. 

Moreover, while mdb_v8 might be loaded, it is possible that it fails to get the V8 version information from the core dump being loaded, which would mean that the mdb_v8 version used is incompatible with the version of Node.js being used. So I'm not sure if _just_ checking for the mdb_v8 version is sufficient, and I think that checking for the V8 version is a better indicator of the mdb_v8 module being successfully loaded.

Should we instead be reading the whole set of lines and look for the same V8 version string?

**Review by misterdjules — COMMENTED** [review]
Thank you for doing this! Suggested a different way to tackle this, let me know what you think.

File: lib/mdb/mdb.js (hunk 1 above)
Comment (rjloura) [reply lib/mdb/mdb.js]: Updated PR.  Note that I left the expected version string format the same even though it has 4 levels of versioning and the regex only verifies that there are at least 3.  I figured this would be a more backwards compatible change.

**Comment by misterdjules** [comment]
Thank you for integrating the feedback into this PR! Just as a formality before we merge this: how did you test this change?

Is it too much work for you to test that both with the latest mdb_v8 version and older versions (like version 1.0.0 that you can download using `curl -O https://us-east.manta.joyent.com/Joyent_Dev/public/mdb_v8/v1.0.0/mdb_v8_ia32.so`)?

If it's too much work, that's fine, I think that this change is fairly safe and I don't really have the time to do that testing myself.

Thanks again!

**Comment by rjloura** [comment]
It's not a problem.  I'll test with 1.0.0 when I have some cycles and let you know.  I tested with 1.3.0 by simply copying `mdb.js` into `/opt/local/lib/node_modules/node-debug-school/lib/mdb/mdb.js`, and running `node-debug-school` as root.

```
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b /home/rui]# uname -a
SunOS 10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b 5.11 joyent_20180810T005956Z i86pc i386 i86pc Solaris
```

**Comment by rjloura** [comment]
For testing mdb_v8 v1.0.0 I:
1. Copied over the both the ia32 and the amd64 v1.0.0 modules from https://us-east.manta.joyent.com/Joyent_Dev/public/mdb_v8/v1.0.0/ to `/root` and `/root/amd64` respectively.
2. temporarily modified the mdb v8 load command in the source: https://github.com/joyent/node-debug-school/blob/master/lib/platform/platform.js#L34 to: `var mdbLoadV8Command = 'echo "::load v8" | mdb -L /root ' + coreFilePath;`
3. Ran `node-debug-school` and confirmed the platform check passed and the main menu was displayed.

Additional details:
```
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b ~]# echo "::load v8" | mdb -L /root cores/core.199704
mdb_v8 version: 1.0.0 (release, from c95ca32)
V8 version: 3.28.71.19
Autoconfigured V8 support from target
C++ symbol demangling enabled
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b ~]# file v8.so
v8.so:          ELF 32-bit LSB dynamic lib 80386 Version 1, dynamically linked, not stripped, no debugging information available
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b ~]# file amd64/v8.so
amd64/v8.so:    ELF 64-bit LSB dynamic lib AMD64 Version 1, dynamically linked, not stripped, no debugging information available
[root@10df76c6-720e-6ab5-d94b-b0a0ca0a1b1b ~]# 
```

**Review by misterdjules — APPROVED** [review]

**Comment by misterdjules** [comment]
@rjloura Looks good to me! I don't have write access to this repo anymore, but you probably do, so feel free to merge this!
